In [1]:
import pandas as pd

In [2]:
import os
os.listdir()

['chipotle_Ex2.csv', 'chipotle.ipynb', '.ipynb_checkpoints']

In [10]:
chipo=pd.read_csv('chipotle_Ex2.csv')

In [12]:
chipo.head(10)

,Unnamed: 0,order_id,quantity,item_name,choice_description,item_price
0,0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,1,Izze,[Clementine],$3.39
2,2,1,1,Nantucket Nectar,[Apple],$3.39
3,3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,6,3,1,Side of Chips,NaN,$1.69
7,7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [13]:
chipo.shape[0]

4622

In [14]:
chipo.columns

Index(['Unnamed: 0', 'order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [15]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          4622 non-null   int64
 1   order_id            4622 non-null   int64
 2   quantity            4622 non-null   int64
 3   item_name           4622 non-null   object
 4   choice_description  3376 non-null   object
 5   item_price          4622 non-null   object
dtypes: int64(3), object(3)
memory usage: 216.8+ KB

In [16]:
chipo.describe()

        Unnamed: 0     order_id     quantity
count  4622.000000  4622.000000  4622.000000
mean   2310.500000   927.254868     1.075725
std    1334.400802   528.890796     0.410186
min       0.000000     1.000000     1.000000
25%    1155.250000   477.250000     1.000000
50%    2310.500000   926.000000     1.000000
75%    3465.750000  1393.000000     1.000000
max    4621.000000  1834.000000    15.000000

In [17]:
chipo.isnull().sum()

Unnamed: 0               0
order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [18]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

In [20]:
chipo['item_name'].value_counts().head(1)

item_name
Chicken Bowl    726
Name: count, dtype: int64

In [22]:
chipo['choice_description'].value_counts().head(1)

choice_description
[Diet Coke]    134
Name: count, dtype: int64

In [23]:
chipo['quantity'].sum()

4972

In [24]:
chipo['item_price'].dtype

dtype('O')

In [27]:
chipo['item_price']= chipo['item_price'].apply(lambda x : float (x.replace ('$', '')))

In [28]:
chipo['item_price'].dtype

dtype('float64')

In [31]:
total_revenue= (chipo['quantity']* chipo[ 'item_price']).sum()
print (f"Total revenue : $ {total_revenue:,.2f}")

Total revenue : $ 39,237.02

In [32]:
chipo['order_id'].nunique()

1834

In [38]:
chipo['revenue']= chipo['quantity']*chipo['item_price']

In [41]:
revenue_per_order= chipo.groupby('order_id')['revenue'].sum().mean()
print (f"Revenue per order: $ {revenue_per_order: .2f}")

Revenue per order: $  21.39

In [42]:
len(chipo['item_name'].unique())

50